version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-brewery
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_EXTRA_ARGS: "--nio --host 0.0.0.0 --http-host 0.0.0.0 --relax-jolokia"
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  eureka:
    build: ../my-eureka
    ports:
      - "8761:8761"

  config-server:
    build: ../my-config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka

  inventory-service:
    build: ../my-inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - config-server
      - mysql
      - artemis
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql


  order-service:
    build: ../my-order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql

  beer-service:
    build: ../my-beer-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql

  api-gateway:
    build: ../my-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
      - beer-service
      - order-service
      - inventory-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery