version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-brewery
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - ../../scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure

  artemis:
    image: quay.io/artemiscloud/activemq-artemis-broker
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      AMQ_EXTRA_ARGS: "--nio --host 0.0.0.0 --http-host 0.0.0.0 --relax-jolokia"
      AMQ_USER: "admin"
      AMQ_PASSWORD: "admin"
    restart: on-failure

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
      - "5601:5601"
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
        - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
        - /var/lib/docker/containers:/var/lib/docker/containers:ro
        - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: unless-stopped

  eureka:
    build: ../../../../../my-eureka
    ports:
      - "8761:8761"
    restart: on-failure

  config-server:
    build: ../../../../../my-config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
    restart: on-failure

  inventory-service:
    build: ../../../../../my-inventory-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - config-server
      - mysql
      - artemis
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"


  order-service:
    build: ../../../../../my-order-service
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  beer-service:
    build: ../../../../../my-beer-service
    ports:
      - "8080:8080"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      spring.cloud.config.uri: http://config-server:8888
      SPRING_PROFILES_ACTIVE: localmysql,local-discovery
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: artemis
      DATABASE_HOST: mysql
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  api-gateway:
    build: ../../../../../my-gateway
    ports:
      - "9090:9090"
    depends_on:
      - eureka
      - artemis
      - config-server
      - mysql
      - beer-service
      - order-service
      - inventory-service
    environment:
      eureka.client.serviceUrl.defaultZone: http://eureka:8761/eureka
      SPRING_PROFILES_ACTIVE: local-discovery
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"